name: hello-world
on: push
jobs:
  cont-integration:
    runs-on: ubuntu-latest #github-runner
    steps:
      - name: pipeline init
        run: echo "Pipeline Init"
        
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: secrets scanning  
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Iac Scanning
        run: echo "Iac Scannign using Checkov"
        
  cont-deployment:
    runs-on: ubuntu-latest #github-runner
    steps:
      - name: Deploy Staging
        run: echo "Deploy Staging in EKS"
        
      - name: Infra scanning
        run: echo "Infra scanning using Open VAS"
        
      - name: Deploy Prod
        run: echo "Deploy Prod in EKS"
