name: hello-world

on: push

jobs:
  cont-integration:
    runs-on: ubuntu-latest
    steps:
      - name: pipeline init
        run: echo "Pipeline Init"
        
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: secrets scanning
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: IaC Scanning
        run: echo "IaC Scanning using Checkov"
        
  cont-deployment:
    runs-on: ubuntu-latest
    needs: cont-integration   # ðŸ‘ˆ waits for integration job
    steps:
      - name: Deploy Staging
        run: echo "Deploy Staging in EKS"
        
      - name: Infra scanning
        run: echo "Infra scanning using OpenVAS"
        
      - name: Deploy Prod
        run: echo "Deploy Prod in EKS"
